"""adding start_date column to trip model.

Revision ID: 40880e19ca2f
Revises: 59b0936ff419
Create Date: 2025-06-10 22:40:12.533627

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40880e19ca2f'
down_revision: str | None = '59b0936ff419'
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('trips', 'start_time')

    # ### end Alembic commands ###
