"""removing snowboard/ski data.

Revision ID: 5d168b3f4415
Revises: 7955dc1662a6
Create Date: 2025-06-23 00:18:41.630148

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d168b3f4415'
down_revision: str | None = '7955dc1662a6'
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rider_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rider_type', postgresql.ENUM('skier', 'snowboarder', name='rider_type'), autoincrement=False, nullable=True))
   
    # ### end Alembic commands ###
